// MODULE FOR ALL ACTIONS
// Still needs to be mapped to action_creators and reducers
export const SET_INITIAL_STATE = "SET_INITIAL_STATE"

export const AUTH_ACTIONS = {
  SIGN_IN: "SIGN_IN",
  SIGN_OUT: "SIGN_OUT"
}

export const UPLOAD_ACTIONS = {
  TOGGLE_UPLOAD_MODAL: "TOGGLE_UPLOAD_MODAL",
  UPLOAD: "UPLOAD"
}

export const CHANGE_VIEW = "CHANGE_VIEW"

export const CHANGE_RUNTYPE = "CHANGE_RUNTYPE"

export const RUNVIEW_ACTIONS = {
  TOGGLE_DATASPACE_MODALS: "TOGGLE_DATASPACE_MODALS",
  CHANGE_OBS_SET: "CHANGE_OBS_SET",
  CHANGE_OBS: "CHANGE_OBS",
  UPDATE_PATHWAYS_MODAL_FILTERS: "UPDATE_PATHWAYS_MODAL_FILTERS",
  CHANGE_PATHWAYS: "CHANGE_PATHWAYS"
}

export const GRAPHVIS_ACTIONS = {
  GRAPHVIS: "GRAPHVIS",
  SELECT_PATHWAY: "SELECT_PATHWAY",
  SELECT_OBSERVATION: "SELECT_OBSERVATION"
}

export const INFERENCE_SUCCESS = "INFERENCE_SUCCESS"

export const HEATMAP_ACTIONS = {
  HEATMAP: "HEATMAP",
  SELECT_RESULT: "SELECT_RESULT",
  SELECT_PATHWAY: "SELECT_PATHWAY",
  SELECT_STATE: "SELECT_STATE"
}
